#!/bin/bash
# -*- mode: sh; -*-
#  build script for GitHub actions

YUM=$(command -v yum)
APT=$(command -v apt-get)
DNF=$(command -v dnf)
CPANM=$(command -v cpanm)

set -ex

if test -n "$APT"; then
    apt-get install -y git gcc make automake curl autoconf
elif test -n "$DNF"; then
    dnf install -y --allowerasing gcc git curl automake make autoconf perl-core tar
elif test -n "$YUM"; then
    yum install -y gcc git curl automake make autoconf perl-core tar
fi

if test -z "$CPANM"; then
  curl -L https://cpanmin.us | perl - App::cpanminus
fi

# Perl module dependencies
for a in $(cat cpan/*requires | perl -ne 'chomp; ($a,$b)=split/\s+/; printf "%s%s\n", $a, $b ne "0" ? "\@$b" : "";'); do \
    cpanm -n -v $a; \
done

./bootstrap
./configure --prefix=/usr/local --with-perl5libdir

if make; then
    make install
else
    echo "ERROR: make failed"
    false
fi

cd cpan
PATH=/usr/local/bin:$PATH make cpan
if test -e CPAN-Maker-*.tar.gz; then
    cpanm -n -v CPAN-Maker-*.tar.gz
    perl -MFile::Process -e 'print $File::Process::VERSION;'
    perl -MCPAN::Maker -e 'print $CPAN::Maker::VERSION;'
else
    echo "ERROR: make cpan failed"
    false
fi
