name: make-cpan-dist
on:
  push:
    branches: [ master ]
jobs:
  test-module:
    runs-on: ubuntu-latest
    container:
      image: perl:5.40-bookworm
    steps:
      - uses: actions/checkout@v4

      - name: build
        run: ./build
